package sop_corba;


/**
* sop_corba/solucion.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from registro.idl
* martes 15 de mayo de 2018 11:24:59 AM COT
*/

public interface solucion extends solucionOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface solucion
