package sop_corba;

/**
* sop_corba/solucionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from registro.idl
* martes 15 de mayo de 2018 11:24:59 AM COT
*/

public final class solucionHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.solucion value = null;

  public solucionHolder ()
  {
  }

  public solucionHolder (sop_corba.solucion initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.solucionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.solucionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.solucionHelper.type ();
  }

}
