package sop_corba;


/**
* sop_corba/solucionHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from registro.idl
* martes 15 de mayo de 2018 08:00:45 AM COT
*/

abstract public class solucionHelper
{
  private static String  _id = "IDL:sop_corba/solucion:1.0";

  public static void insert (org.omg.CORBA.Any a, sop_corba.solucion that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static sop_corba.solucion extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (sop_corba.solucionHelper.id (), "solucion");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static sop_corba.solucion read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_solucionStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, sop_corba.solucion value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static sop_corba.solucion narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof sop_corba.solucion)
      return (sop_corba.solucion)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      sop_corba._solucionStub stub = new sop_corba._solucionStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static sop_corba.solucion unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof sop_corba.solucion)
      return (sop_corba.solucion)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      sop_corba._solucionStub stub = new sop_corba._solucionStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
