package sop_corba;


/**
* sop_corba/sop_corbaHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from registro.idl
* martes 15 de mayo de 2018 07:33:08 AM COT
*/

abstract public class sop_corbaHelper
{
  private static String  _id = "IDL:sop_corba/sop_corba:1.0";

  public static void insert (org.omg.CORBA.Any a, sop_corba that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static sop_corba extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (sop_corbaHelper.id (), "sop_corba");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static sop_corba read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_sop_corbaStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, sop_corba value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static sop_corba narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof sop_corba)
      return (sop_corba)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _sop_corbaStub stub = new _sop_corbaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static sop_corba unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof sop_corba)
      return (sop_corba)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _sop_corbaStub stub = new _sop_corbaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
