package sop_corba;


/**
* sop_corba/sop_corba.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from registro.idl
* martes 15 de mayo de 2018 07:55:25 AM COT
*/

public interface sop_corba extends sop_corbaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface sop_corba
