package sop_corba;


/**
* sop_corba/sop_corbaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from registro.idl
* martes 15 de mayo de 2018 07:55:25 AM COT
*/

public interface sop_corbaOperations 
{
  void comenzarJuego ();
  String adivinarLetra (char letra);
  boolean adivinarPalabra (String palabra);
  int longitudPalabra ();
  int numeroIntentos ();
  String mostrarPalabras ();
} // interface sop_corbaOperations
